Algoritmo "Média do Aluno"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Edilene Veneruchi
// Descrição   : Exercício nº23
// Autor(a)    : Igor Françozo
// Data atual  : 23/02/2022
Var
ang1,ang2, result_ang : real


Inicio
escreval ("Informe o primeiro angulo:")
leia(ang1)
escreval ("Informe o segundo angulo:")
leia(ang2)
result_ang <- 180 - (ang1+ang2)
escreval ("Terceiro ângulo equivale:", result_ang)

fimalgoritmo